name: Bug report
description: Report a bug to help us improve
labels: [bug]
title: "fix: [short summary]"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear steps
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version / commit
