name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
title: "feat: [short summary]"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
