name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      sqlite:
        image: keinos/sqlite3
        options: >-
          --health-cmd "sqlite3 --version" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, pdo_sqlite
      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Copy env
        run: cp .env.example .env || true
      - name: Generate key
        run: php artisan key:generate
      - name: Prepare database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --force --no-interaction
      - name: Run tests
        run: php artisan test --env=testing
